In [1]:
import pandas as pd
df = pd.read_csv("../data/players_stats.csv")
df.head()

,Tournament,Stage,Match Type,Player,Teams,Agents,Rounds Played,Rating,Average Combat Score,Kills:Deaths,...,First Deaths Per Round,Headshot %,Clutch Success %,Clutches (won/played),Maximum Kills in a Single Map,Kills,Deaths,Assists,First Kills,First Deaths
0,Valorant Champions 2025,Playoffs,Upper Quarterfinals,Boo,Team Heretics,astra,26,0.68,129.0,0.61,...,0.12,44%,NaN,0/4,11,11,18,4,3,3
1,Valorant Champions 2025,Playoffs,Upper Quarterfinals,Boo,Team Heretics,omen,19,0.46,98.0,0.40,...,0.26,37%,33%,1/3,6,6,15,5,1,5
2,Valorant Champions 2025,Playoffs,Upper Quarterfinals,Boo,Team Heretics,"astra, omen",45,0.59,114.0,0.52,...,0.18,41%,14%,1/7,11,17,33,9,4,8
3,Valorant Champions 2025,Playoffs,Upper Quarterfinals,RieNs,Team Heretics,fade,26,1.21,219.0,1.13,...,0.04,23%,33%,1/3,18,18,16,10,2,1
4,Valorant Champions 2025,Playoffs,Upper Quarterfinals,RieNs,Team Heretics,sova,19,1.02,220.0,0.75,...,0.05,28%,NaN,0/4,12,12,16,5,1,1

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17996 entries, 0 to 17995
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Tournament                      17996 non-null  str
 1   Stage                           17996 non-null  str
 2   Match Type                      17996 non-null  str
 3   Player                          17996 non-null  str
 4   Teams                           17996 non-null  str
 5   Agents                          17996 non-null  str
 6   Rounds Played                   17996 non-null  int64
 7   Rating                          16604 non-null  float64
 8   Average Combat Score            17986 non-null  float64
 9   Kills:Deaths                    17996 non-null  float64
 10  Kill, Assist, Trade, Survive %  16692 non-null  str
 11  Average Damage Per Round        16626 non-null  float64
 12  Kills Per Round                 17996 non-null  float64
 13  Assists Per Round               17996 non-null  float64
 14  First Kills Per Round           16645 non-null  float64
 15  First Deaths Per Round          16646 non-null  float64
 16  Headshot %                      16688 non-null  str
 17  Clutch Success %                6659 non-null   str
 18  Clutches (won/played)           13263 non-null  str
 19  Maximum Kills in a Single Map   17996 non-null  int64
 20  Kills                           17996 non-null  int64
 21  Deaths                          17996 non-null  int64
 22  Assists                         17996 non-null  int64
 23  First Kills                     17996 non-null  int64
 24  First Deaths                    17996 non-null  int64
dtypes: float64(8), int64(7), str(10)
memory usage: 3.4 MB

In [3]:
df_scores = pd.read_csv("../data/scores.csv")
df_scores.head()

,Tournament,Stage,Match Type,Match Name,Team A,Team B,Team A Score,Team B Score,Match Result
0,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Paper Rex,Xi Lai Gaming,2,0,Paper Rex won
1,Valorant Champions 2025,Group Stage,Opening (A),GIANTX vs Sentinels,GIANTX,Sentinels,2,1,GIANTX won
2,Valorant Champions 2025,Group Stage,Opening (C),NRG vs EDward Gaming,Mega Minors,EDward Gaming,2,0,NRG won
3,Valorant Champions 2025,Group Stage,Opening (C),Team Liquid vs DRX,Team Liquid,DRX,0,2,DRX won
4,Valorant Champions 2025,Group Stage,Opening (D),Dragon Ranger Gaming vs T1,Dragon Ranger Gaming,T1,0,2,T1 won

In [4]:
df_scores.duplicated(subset=["Tournament", "Stage", "Match Type"]).sum()

np.int64(311)

In [5]:
df_scores.duplicated(subset=["Tournament", "Stage", "Match Name"]).sum()

np.int64(8)

In [6]:
df_scores.duplicated(subset=["Tournament", "Stage", "Match Type", "Match Name"]).sum()

np.int64(0)

In [7]:
df.columns

Index(['Tournament', 'Stage', 'Match Type', 'Player', 'Teams', 'Agents',
       'Rounds Played', 'Rating', 'Average Combat Score', 'Kills:Deaths',
       'Kill, Assist, Trade, Survive %', 'Average Damage Per Round',
       'Kills Per Round', 'Assists Per Round', 'First Kills Per Round',
       'First Deaths Per Round', 'Headshot %', 'Clutch Success %',
       'Clutches (won/played)', 'Maximum Kills in a Single Map', 'Kills',
       'Deaths', 'Assists', 'First Kills', 'First Deaths'],
      dtype='str')

In [8]:
df_teams = pd.read_csv("../data/team_mapping.csv")
df_teams.head()

  Abbreviated      Full Name
0         PRX      Paper Rex
1         XLG  Xi Lai Gaming
2          GX         GIANTX
3         SEN      Sentinels
4         NRG            NRG

In [25]:
"Mega Minors" in df_teams["Full Name"].values

False

In [26]:
"Mega Minors" in df_teams["Abbreviated"].values

False

In [27]:
df["Teams"].unique()

<StringArray>
[                     'Team Heretics',                             'GIANTX',
                         'G2 Esports',                               'MIBR',
                                'DRX',                             'FNATIC',
                          'Paper Rex',                        'Mega Minors',
                          'Sentinels',                      'Xi Lai Gaming',
                    'Bilibili Gaming',                     'Rex Regum Qeon',
                        'Team Liquid',                      'EDward Gaming',
               'Dragon Ranger Gaming',                                 'T1',
                        'BBL Esports',                      'Natus Vincere',
                       'Karmine Corp',                      'Team Vitality',
                       'Gentle Mates',                                'KOI',
                        'FUT Esports',                              'Apeks',
                           'LEVIATÁN',                        '100 Thieves',
                             'Cloud9',                      'Evil Geniuses',
                        'KRÜ Esports',                      '2Game Esports',
                              'FURIA',                               'LOUD',
                  'Nongshim RedForce',                              'TALON',
                              'Gen.G',                 'DetonatioN FocusMe',
                     'Global Esports',                        'Team Secret',
                      'ZETA DIVISION',                       'BOOM Esports',
                         'All Gamers',                              'TYLOO',
                      'Trace Esports',                    'FunPlus Phoenix',
                 'Titan Esports Club',                     'Wolves Esports',
                       'Nova Esports',                        'JDG Esports',
           'Pure Aim, Wolves Esports', 'Precise Defeat, Titan Esports Club',
            'Pure Aim, Trace Esports',             'Nova Esports, Pure Aim',
     'Precise Defeat, Wolves Esports',       'Nova Esports, Precise Defeat',
          'FunPlus Phoenix, Pure Aim',        'JDG Esports, Precise Defeat',
    'FunPlus Phoenix, Precise Defeat',      'Sentinels, Team International']
Length: 58, dtype: str

In [28]:
df["Teams"].nunique()

58

In [29]:
df["Teams"].str.contains(",").sum()

np.int64(58)

In [30]:
df_clean = df[~df["Teams"].str.contains(",")]

In [31]:
df.shape

(17996, 25)

In [32]:
df_clean.shape

(17938, 25)

In [33]:
df_clean["Teams"].unique()

<StringArray>
[       'Team Heretics',               'GIANTX',           'G2 Esports',
                 'MIBR',                  'DRX',               'FNATIC',
            'Paper Rex',          'Mega Minors',            'Sentinels',
        'Xi Lai Gaming',      'Bilibili Gaming',       'Rex Regum Qeon',
          'Team Liquid',        'EDward Gaming', 'Dragon Ranger Gaming',
                   'T1',          'BBL Esports',        'Natus Vincere',
         'Karmine Corp',        'Team Vitality',         'Gentle Mates',
                  'KOI',          'FUT Esports',                'Apeks',
             'LEVIATÁN',          '100 Thieves',               'Cloud9',
        'Evil Geniuses',          'KRÜ Esports',        '2Game Esports',
                'FURIA',                 'LOUD',    'Nongshim RedForce',
                'TALON',                'Gen.G',   'DetonatioN FocusMe',
       'Global Esports',          'Team Secret',        'ZETA DIVISION',
         'BOOM Esports',           'All Gamers',                'TYLOO',
        'Trace Esports',      'FunPlus Phoenix',   'Titan Esports Club',
       'Wolves Esports',         'Nova Esports',          'JDG Esports']
Length: 48, dtype: str

In [34]:
df_scores["Team A"].unique()

<StringArray>
[           'Paper Rex',               'GIANTX',          'Mega Minors',
          'Team Liquid', 'Dragon Ranger Gaming',           'G2 Esports',
      'Bilibili Gaming',       'Rex Regum Qeon',                  'DRX',
        'Team Heretics',                 'MIBR',        'Xi Lai Gaming',
                   'T1',               'FNATIC',               'Cloud9',
             'LEVIATÁN',        'Evil Geniuses',          '100 Thieves',
            'Sentinels',        '2Game Esports',                'FURIA',
                 'LOUD',          'KRÜ Esports',           'Team Alpha',
        'Natus Vincere',        'Team Vitality',          'FUT Esports',
                'Apeks',         'Gentle Mates',                  'KOI',
          'BBL Esports',          'Team France',         'BOOM Esports',
    'Nongshim RedForce',        'ZETA DIVISION',       'Global Esports',
                'TALON',                'Gen.G',           'Team World',
        'EDward Gaming',           'All Gamers',       'Wolves Esports',
          'JDG Esports',        'Trace Esports',      'FunPlus Phoenix',
                'TYLOO',   'Titan Esports Club',         'Nova Esports',
             'Pure Aim',         'Karmine Corp',   'DetonatioN FocusMe',
          'Team Secret',   'Team International']
Length: 53, dtype: str

In [35]:
df_scores["Team B"].unique()

<StringArray>
[       'Xi Lai Gaming',            'Sentinels',        'EDward Gaming',
                  'DRX',                   'T1',        'Team Heretics',
                 'MIBR',               'FNATIC',               'GIANTX',
          'Mega Minors',       'Rex Regum Qeon', 'Dragon Ranger Gaming',
          'Team Liquid',           'G2 Esports',            'Paper Rex',
                'FURIA',                 'LOUD',        '2Game Esports',
          'KRÜ Esports',        'Evil Geniuses',             'LEVIATÁN',
               'Cloud9',          '100 Thieves',           'Team Omega',
                'Apeks',         'Gentle Mates',                  'KOI',
          'BBL Esports',         'Karmine Corp',        'Natus Vincere',
        'Team Vitality',            'Team EMEA',                'TALON',
          'Team Secret',                'Gen.G',       'Global Esports',
   'DetonatioN FocusMe',    'Nongshim RedForce',        'ZETA DIVISION',
     'Glory Once Again',   'Titan Esports Club',                'TYLOO',
      'FunPlus Phoenix',         'Nova Esports',        'Trace Esports',
       'Wolves Esports',      'Bilibili Gaming',           'All Gamers',
          'JDG Esports',       'Precise Defeat',          'FUT Esports',
         'BOOM Esports',        'Team Thailand']
Length: 53, dtype: str

In [36]:
pd.concat([df_scores["Team A"], df_scores["Team B"]])

0                 Paper Rex
1                    GIANTX
2               Mega Minors
3               Team Liquid
4      Dragon Ranger Gaming
               ...
498           Xi Lai Gaming
499           Trace Esports
500           EDward Gaming
501           EDward Gaming
502           EDward Gaming
Length: 1006, dtype: str

In [37]:
teams_players = set(df_clean["Teams"].unique())

In [39]:
teams_players - set(pd.concat([df_scores["Team A"], df_scores["Team B"]]))

set()

In [40]:
"NRG" in teams_players

False

In [41]:
set(pd.concat([df_scores["Team A"], df_scores["Team B"]])) - teams_players

{'Glory Once Again',
 'Precise Defeat',
 'Pure Aim',
 'Team Alpha',
 'Team EMEA',
 'Team France',
 'Team International',
 'Team Omega',
 'Team Thailand',
 'Team World'}

In [42]:
df_scores.columns

Index(['Tournament', 'Stage', 'Match Type', 'Match Name', 'Team A', 'Team B',
       'Team A Score', 'Team B Score', 'Match Result'],
      dtype='str')

In [55]:
side_a = df_scores.rename(columns={"Team A": "Teams","Team B": "opponent", "Team A Score": "team_score", "Team B Score": "opp_score"})

In [56]:
side_a.columns

Index(['Tournament', 'Stage', 'Match Type', 'Match Name', 'Teams', 'opponent',
       'team_score', 'opp_score', 'Match Result'],
      dtype='str')

In [57]:
side_b = df_scores.rename(columns={"Team B": "Teams","Team A": "opponent", "Team B Score": "team_score", "Team A Score": "opp_score"})

In [58]:
side_b.columns

Index(['Tournament', 'Stage', 'Match Type', 'Match Name', 'opponent', 'Teams',
       'opp_score', 'team_score', 'Match Result'],
      dtype='str')

In [59]:
df_scores.shape

(503, 9)

In [60]:
scores_long = pd.concat([side_a, side_b], ignore_index=True)

In [61]:
scores_long.shape

(1006, 9)

In [62]:
scores_long.columns

Index(['Tournament', 'Stage', 'Match Type', 'Match Name', 'Teams', 'opponent',
       'team_score', 'opp_score', 'Match Result'],
      dtype='str')

In [67]:
scores_long["win"]= (scores_long["team_score"] > scores_long["opp_score"]).astype(int)

In [68]:
scores_long.columns

Index(['Tournament', 'Stage', 'Match Type', 'Match Name', 'Teams', 'opponent',
       'team_score', 'opp_score', 'Match Result', 'win'],
      dtype='str')

In [69]:
scores_long["win"].mean()

np.float64(0.5)

In [70]:
df_clean.columns

Index(['Tournament', 'Stage', 'Match Type', 'Player', 'Teams', 'Agents',
       'Rounds Played', 'Rating', 'Average Combat Score', 'Kills:Deaths',
       'Kill, Assist, Trade, Survive %', 'Average Damage Per Round',
       'Kills Per Round', 'Assists Per Round', 'First Kills Per Round',
       'First Deaths Per Round', 'Headshot %', 'Clutch Success %',
       'Clutches (won/played)', 'Maximum Kills in a Single Map', 'Kills',
       'Deaths', 'Assists', 'First Kills', 'First Deaths'],
      dtype='str')

In [71]:
scores_long.columns

Index(['Tournament', 'Stage', 'Match Type', 'Match Name', 'Teams', 'opponent',
       'team_score', 'opp_score', 'Match Result', 'win'],
      dtype='str')

In [72]:
df_merged = pd.merge(df_clean, scores_long, on=['Tournament', 'Stage', 'Match Type', 'Teams'], how="left")

In [73]:
df_merged.shape

(18365, 31)

In [74]:
scores_long[scores_long.duplicated(subset=['Tournament', 'Stage', 'Match Type', 'Teams'], keep=False)]

,Tournament,Stage,Match Type,Match Name,Teams,opponent,team_score,opp_score,Match Result,win
120,VCT 2025: Pacific Stage 2,Group Stage,Week 1,BOOM Esports vs TALON,BOOM Esports,TALON,0,2,TALON won,0
121,VCT 2025: Pacific Stage 2,Group Stage,Week 1,Nongshim RedForce vs Team Secret,Nongshim RedForce,Team Secret,2,1,Nongshim RedForce won,1
122,VCT 2025: Pacific Stage 2,Group Stage,Week 1,T1 vs Paper Rex,T1,Paper Rex,0,2,Paper Rex won,0
123,VCT 2025: Pacific Stage 2,Group Stage,Week 1,DRX vs Gen.G,DRX,Gen.G,0,2,Gen.G won,0
124,VCT 2025: Pacific Stage 2,Group Stage,Week 1,Rex Regum Qeon vs Global Esports,Rex Regum Qeon,Global Esports,0,2,Global Esports won,0
125,VCT 2025: Pacific Stage 2,Group Stage,Week 1,ZETA DIVISION vs DetonatioN FocusMe,ZETA DIVISION,DetonatioN FocusMe,1,2,DetonatioN FocusMe won,0
126,VCT 2025: Pacific Stage 2,Group Stage,Week 1,DRX vs Nongshim RedForce,DRX,Nongshim RedForce,2,1,DRX won,1
127,VCT 2025: Pacific Stage 2,Group Stage,Week 1,BOOM Esports vs T1,BOOM Esports,T1,0,2,T1 won,0
128,VCT 2025: Pacific Stage 2,Group Stage,Week 1,Global Esports vs Team Secret,Global Esports,Team Secret,1,2,Team Secret won,0
129,VCT 2025: Pacific Stage 2,Group Stage,Week 1,Paper Rex vs DetonatioN FocusMe,Paper Rex,DetonatioN FocusMe,2,0,Paper Rex won,1
130,VCT 2025: Pacific Stage 2,Group Stage,Week 1,TALON vs ZETA DIVISION,TALON,ZETA DIVISION,2,0,TALON won,1
131,VCT 2025: Pacific Stage 2,Group Stage,Week 1,Rex Regum Qeon vs Gen.G,Rex Regum Qeon,Gen.G,2,1,Rex Regum Qeon won,1
169,VCT 2025: China Stage 2,Group Stage,Week 2,Trace Esports vs TYLOO,Trace Esports,TYLOO,0,2,TYLOO won,0
171,VCT 2025: China Stage 2,Group Stage,Week 2,All Gamers vs Wolves Esports,All Gamers,Wolves Esports,2,0,All Gamers won,1
173,VCT 2025: China Stage 2,Group Stage,Week 2,TYLOO vs Titan Esports Club,TYLOO,Titan Esports Club,2,0,TYLOO won,1
174,VCT 2025: China Stage 2,Group Stage,Week 2,Trace Esports vs EDward Gaming,Trace Esports,EDward Gaming,2,1,Trace Esports won,1
177,VCT 2025: China Stage 2,Group Stage,Week 3,Titan Esports Club vs Bilibili Gaming,Titan Esports Club,Bilibili Gaming,0,2,Bilibili Gaming won,0
178,VCT 2025: China Stage 2,Group Stage,Week 3,FunPlus Phoenix vs Dragon Ranger Gaming,FunPlus Phoenix,Dragon Ranger Gaming,2,1,FunPlus Phoenix won,1
181,VCT 2025: China Stage 2,Group Stage,Week 3,Titan Esports Club vs JDG Esports,Titan Esports Club,JDG Esports,1,2,JDG Esports won,0
182,VCT 2025: China Stage 2,Group Stage,Week 3,Bilibili Gaming vs Trace Esports,Bilibili Gaming,Trace Esports,1,2,Trace Esports won,0
185,VCT 2025: China Stage 2,Group Stage,Week 4,Nova Esports vs Xi Lai Gaming,Nova Esports,Xi Lai Gaming,0,2,Xi Lai Gaming won,0
186,VCT 2025: China Stage 2,Group Stage,Week 4,EDward Gaming vs JDG Esports,EDward Gaming,JDG Esports,2,1,EDward Gaming won,1
189,VCT 2025: China Stage 2,Group Stage,Week 4,Nova Esports vs Wolves Esports,Nova Esports,Wolves Esports,2,1,Nova Esports won,1
623,VCT 2025: Pacific Stage 2,Group Stage,Week 1,BOOM Esports vs TALON,TALON,BOOM Esports,2,0,TALON won,1
624,VCT 2025: Pacific Stage 2,Group Stage,Week 1,Nongshim RedForce vs Team Secret,Team Secret,Nongshim RedForce,1,2,Nongshim RedForce won,0
625,VCT 2025: Pacific Stage 2,Group Stage,Week 1,T1 vs Paper Rex,Paper Rex,T1,2,0,Paper Rex won,1
626,VCT 2025: Pacific Stage 2,Group Stage,Week 1,DRX vs Gen.G,Gen.G,DRX,2,0,Gen.G won,1
627,VCT 2025: Pacific Stage 2,Group Stage,Week 1,Rex Regum Qeon vs Global Esports,Global Esports,Rex Regum Qeon,2,0,Global Esports won,1
628,VCT 2025: Pacific Stage 2,Group Stage,Week 1,ZETA DIVISION vs DetonatioN FocusMe,DetonatioN FocusMe,ZETA DIVISION,2,1,DetonatioN FocusMe won,1
629,VCT 2025: Pacific Stage 2,Group Stage,Week 1,DRX vs Nongshim RedForce,Nongshim RedForce,DRX,1,2,DRX won,0
630,VCT 2025: Pacific Stage 2,Group Stage,Week 1,BOOM Esports vs T1,T1,BOOM Esports,2,0,T1 won,1
631,VCT 2025: Pacific Stage 2,Group Stage,Week 1,Global Esports vs Team Secret,Team Secret,Global Esports,2,1,Team Secret won,1
632,VCT 2025: Pacific Stage 2,Group Stage,Week 1,Paper Rex vs DetonatioN FocusMe,DetonatioN FocusMe,Paper Rex,0,2,Paper Rex won,0
633,VCT 2025: Pacific Stage 2,Group Stage,Week 1,TALON vs ZETA DIVISION,ZETA DIVISION,TALON,0,2,TALON won,0
634,VCT 2025: Pacific Stage 2,Group Stage,Week 1,Rex Regum Qeon vs Gen.G,Gen.G,Rex Regum Qeon,1,2,Rex Regum Qeon won,0
672,VCT 2025: China Stage 2,Group Stage,Week 2,Trace Esports vs TYLOO,TYLOO,Trace Esports,2,0,TYLOO won,1
674,VCT 2025: China Stage 2,Group Stage,Week 2,All Gamers vs Wolves Esports,Wolves Esports,All Gamers,0,2,All Gamers won,0
678,VCT 2025: China Stage 2,Group Stage,Week 2,Dragon Ranger Gaming vs All Gamers,All Gamers,Dragon Ranger Gaming,1,2,Dragon Ranger Gaming won,0
679,VCT 2025: China Stage 2,Group Stage,Week 2,Xi Lai Gaming vs Wolves Esports,Wolves Esports,Xi Lai Gaming,0,2,Xi Lai Gaming won,0
680,VCT 2025: China Stage 2,Group Stage,Week 3,Titan Esports Club vs Bilibili Gaming,Bilibili Gaming,Titan Esports Club,2,0,Bilibili Gaming won,1
681,VCT 2025: China Stage 2,Group Stage,Week 3,FunPlus Phoenix vs Dragon Ranger Gaming,Dragon Ranger Gaming,FunPlus Phoenix,1,2,FunPlus Phoenix won,0
686,VCT 2025: China Stage 2,Group Stage,Week 3,Wolves Esports vs Dragon Ranger Gaming,Dragon Ranger Gaming,Wolves Esports,1,2,Wolves Esports won,0
687,VCT 2025: China Stage 2,Group Stage,Week 3,Xi Lai Gaming vs FunPlus Phoenix,FunPlus Phoenix,Xi Lai Gaming,0,2,Xi Lai Gaming won,0
688,VCT 2025: China Stage 2,Group Stage,Week 4,Nova Esports vs Xi Lai Gaming,Xi Lai Gaming,Nova Esports,2,0,Xi Lai Gaming won,1
689,VCT 2025: China Stage 2,Group Stage,Week 4,EDward Gaming vs JDG Esports,JDG Esports,EDward Gaming,1,2,EDward Gaming won,0
693,VCT 2025: China Stage 2,Group Stage,Week 4,Dragon Ranger Gaming vs Xi Lai Gaming,Xi Lai Gaming,Dragon Ranger Gaming,1,2,Dragon Ranger Gaming won,0
694,VCT 2025: China Stage 2,Group Stage,Week 4,TYLOO vs JDG Esports,JDG Esports,TYLOO,1,2,TYLOO won,0
695,VCT 2025: China Stage 2,Group Stage,Week 4,Bilibili Gaming vs EDward Gaming,EDward Gaming,Bilibili Gaming,0,2,Bilibili Gaming won,0

In [75]:
scores_unique = scores_long[~scores_long.duplicated(subset=['Tournament', 'Stage', 'Match Type', 'Teams'], keep=False)]

In [77]:
scores_unique.shape

(958, 10)

In [78]:
df_merged = pd.merge(df_clean, scores_unique, on=['Tournament', 'Stage', 'Match Type', 'Teams'], how="left")

In [79]:
df_merged.shape

(17938, 31)

In [80]:
df_merged["win"].isna().sum()

np.int64(4660)

In [81]:
df_final = df_merged[df_merged["win"].notna()]